# Alacritty Config TOML

[env]
TERM = "xterm-256color"

[cursor]
style.shape = "Beam"
style.blinking = "Always"
blink_interval = 800

[font]
normal.family = "Hack Nerd Font"
size = 18.0

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.69
blur = true

padding.x = 5
padding.y = 0

dimensions.columns = 90
dimensions.lines = 25

[colors]
cursor.text = "CellBackground"
cursor.cursor = "CellForeground"
